version: '2'

services:
  angular: 
    build: client
    ports:
      - "4200:4200" 
    environment:
      - NODE_ENV=dev

  express:
    build: server 
    ports:
      - "5000:5000"
    links:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017" 
